### ISSUE TITLE
trackeval.utils.TrackEvalException: no seqmap found: evaluate_tracking.seqmap.val

### ISSUE THREAD

**Issue by callzhang** [hailanyi/3D-Multi-Object-Tracker#3]
I have prepared the data and ran `kitti_3DMOT.py` according to readme.md, the following error has thrown. Did I missing something?
```
Traceback (most recent call last):
  File "/home/stardust/yrb/3D-Multi-Object-Tracker/kitti_3DMOT.py", line 167, in <module>
    tracking_val_seq(args)
  File "/home/stardust/yrb/3D-Multi-Object-Tracker/kitti_3DMOT.py", line 160, in tracking_val_seq
    eval_kitti()
  File "/home/stardust/yrb/3D-Multi-Object-Tracker/evaluation_HOTA/scripts/run_kitti.py", line 80, in eval_kitti
    dataset_list = [trackeval.datasets.Kitti2DBox(dataset_config)]
  File "/home/stardust/yrb/3D-Multi-Object-Tracker/evaluation_HOTA/trackeval/datasets/kitti_2d_box.py", line 71, in __init__
    raise TrackEvalException('no seqmap found: ' + os.path.basename(seqmap_file))
trackeval.utils.TrackEvalException: no seqmap found: evaluate_tracking.seqmap.val
```

On line 70, the missing `seqmap_file` was pointing to `/home/stardust/yrb/3D-Multi-Object-Tracker/evaluation_HOTA/../evaluation/data/tracking/evaluate_tracking.seqmap.val`

**Comment by MohamedNagyMostafa** [comment]
same problem !!

**Comment by hailanyi** [comment]
Ok, thanks to point this  evaluation_HOTA path error.
I have fix this bug by updating the codes of [evaluation_HOTA/trackeval/datasets/kitti_2d_box.py ](https://github.com/hailanyi/3D-Multi-Object-Tracker/blob/master/evaluation_HOTA/trackeval/datasets/kitti_2d_box.py) line 20, 21 as follows.

```
            'GT_FOLDER': os.path.join('evaluation/data/tracking'),  # Location of GT data
            'TRACKERS_FOLDER': os.path.join('evaluation/results'),  # Trackers location
```
